version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    environment:
      API_URL: http://a4f674319ba4c4ecca948981c668634a-459882564.us-east-1.elb.amazonaws.com
      DATABASE_URL: postgres://myuser:mypassword@db:5432/mydatabase
    volumes:
      - ./app:/app  # Local 'app' directory mounted to container's /app directory
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:

