name: Push image Demo proxy app to ECR git tag latest
on:
  push:
    branches:
      - main

 
permissions: read-all
jobs:
  build-and-push-demo-proxy-app:
    runs-on: ${{ matrix.os }}
    name: Demo proxy app | OS ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
 
      - name: Print
        run: echo "Pushing to Tag= ${{steps.setvars.outputs.tag}}"
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Push to ECR
        id: push-to-ecr
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: |
          chmod +x ./bin/push_to_ecr.sh
          ./bin/push_to_ecr.sh demo-proxy-app . demo-proxy-app latest-test